# .github/workflows/2-get-user-info.yml
name: 'ℹ️ 2. Get User Info'

on:
  workflow_dispatch:
    inputs:
      user_id:
        description: 'The ID of the user to look up.'
        required: true

jobs:
  run-tool:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - name: Install Dependencies
        run: pip install requests pyotp
      - name: 🔎 Run The Power Tool
        env:
          WORKER_URL: ${{ secrets.WORKER_URL }}
          TOTP_SECRET_KEY: ${{ secrets.TOTP_SECRET_KEY }}
          ACTION: 'get_info'
          USER_ID: ${{ github.event.inputs.user_id }}
        run: python power_tool.py
